### ISSUE TITLE
kernal info retrieval fails on small VMs

### ISSUE THREAD

**Issue by chrisjsewell** [jupyter/nbclient#101]
This is essentially re-opening #95, because #96 adds extra debugging, but it does not fix it.

Basically on nearly every RTD run that calls nbclient, it fails intermittently and is super frustrating 😞 e.g. https://readthedocs.org/projects/sphinx-book-theme/builds/11733784/.
This has happened for both v0.2 and v0.4

The VM they are using is `Standard_D1_v2`

See: https://docs.microsoft.com/en-us/azure/virtual-machines/dv2-dsv2-series?toc=/azure/virtual-machines/linux/toc.json&bc=/azure/virtual-machines/linux/breadcrumb/toc.json#dv2-series

This may be related to #58

**Comment by davidbrochart** [comment]
Did you try with master branch? If so, what does the exception say about `info_msg['content']`?

**Comment by chrisjsewell** [comment]
No good point I should do that.
I messed around with it a load, and have tentatively got it to work, in this case, by removing a code cell.
If it is primarily a memory issue; the retrieval failing because of all the cell outputs now being held in memory, perhaps it would be helpful to put the `language_info` retrieval before the execution of the cells?

**Comment by davidbrochart** [comment]
Yes I think it doesn't hurt putting the `language_info` retrieval before the execution. But if we are out of memory after the execution, we're in pretty bad shape anyway.

**Comment by chrisjsewell** [comment]
Yeh exactly, I don't know if there is a deeper underlying cause (like memory leakage), but I think that would at least be a band aid

**Comment by chrisjsewell** [comment]
Thanks for merging 😄 

FYI, I did just get an error from 0.4.2 on GH actions this time; https://github.com/executablebooks/jupyter-book/pull/911/checks?check_run_id=1035210652:

```python
WARNING: /Users/runner/work/jupyter-book/jupyter-book/docs/file-types/notebooks.ipynb
Traceback (most recent call last):
  File "/Users/runner/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/jupyter_cache/executors/basic.py", line 147, in execute
    None,
  File "/Users/runner/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/jupyter_cache/executors/basic.py", line 155, in execute_single
    nb_bundle.nb, cwd=cwd, timeout=timeout, allow_errors=allow_errors,
  File "/Users/runner/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/Users/runner/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/client.py", line 1082, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/runner/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/runner/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/runner/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/Users/runner/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/client.py", line 536, in async_execute
    'Content is:\n' + str(info_msg['content'])
RuntimeError: Kernel info received message content has no "language_info" key.Content is:
{'status': 'aborted'}
```

Could I be cheeky, and ask for a 0.4.3 release 😬

**Comment by davidbrochart** [comment]
Sure, will do today!

**Comment by chrisjsewell** [comment]
Legend!

**Comment by davidbrochart** [comment]
0.4.3 is out.

**Comment by davidbrochart** [comment]
0.5.0 is out, you should use it instead of 0.4.3, sorry!
