### ISSUE TITLE
atexit._run_exitfuncs error "'session' trait of an AsyncKernelManager instance must be a Session"

### ISSUE THREAD

**Issue by alex-treebeard** [jupyter/nbclient#128]
Hey there, just ran into a pretty thorny issue which occurred when I ran my tests for all but the first to run.

This occurred at 0.5 and 0.4, 0.3 does not have this issue though.

Edit: Running Python 3.7.6 on  Darwin Kernel Version 19.6.0, using NBClient in a pretty standard way:

```python
            c = NotebookClient(
                nb,
                timeout=timeout,
                allow_errors=allow_errors,
                record_timing=True,
            )
            c.execute(cwd=self.filename.parent)
```

Will let you know if I find out more.
```
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Users/asdf/Library/Caches/pypoetry/virtualenvs/nbmake-kabcMfG_-py3.7/lib/python3.7/site-packages/traitlets/traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'session'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/asdf/Library/Caches/pypoetry/virtualenvs/nbmake-kabcMfG_-py3.7/lib/python3.7/site-packages/nbclient/client.py", line 358, in _async_cleanup_kernel
    await ensure_async(self.km.cleanup_resources())
  File "/Users/asdf/Library/Caches/pypoetry/virtualenvs/nbmake-kabcMfG_-py3.7/lib/python3.7/site-packages/jupyter_client/manager.py", line 355, in cleanup_resources
    self.session.parent = None
  File "/Users/asdf/Library/Caches/pypoetry/virtualenvs/nbmake-kabcMfG_-py3.7/lib/python3.7/site-packages/traitlets/traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "/Users/asdf/Library/Caches/pypoetry/virtualenvs/nbmake-kabcMfG_-py3.7/lib/python3.7/site-packages/traitlets/traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "/Users/asdf/Library/Caches/pypoetry/virtualenvs/nbmake-kabcMfG_-py3.7/lib/python3.7/site-packages/traitlets/traitlets.py", line 591, in _validate
    value = self.validate(obj, value)
  File "/Users/asdf/Library/Caches/pypoetry/virtualenvs/nbmake-kabcMfG_-py3.7/lib/python3.7/site-packages/traitlets/traitlets.py", line 1677, in validate
    self.error(obj, value)
  File "/Users/asdf/Library/Caches/pypoetry/virtualenvs/nbmake-kabcMfG_-py3.7/lib/python3.7/site-packages/traitlets/traitlets.py", line 1524, in error
    raise TraitError(e)
traitlets.traitlets.TraitError: The 'session' trait of an AsyncKernelManager instance must be a Session, but a value of class 'jupyter_client.session.Session' (i.e. <jupyter_client.session.Session object at 0x7ffe59f9e890>) was specified.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Users/asdf/Library/Caches/pypoetry/virtualenvs/nbmake-kabcMfG_-py3.7/lib/python3.7/site-packages/traitlets/traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'session'
```

**Comment by xmnlab** [comment]
@alex-treebeard I tried with version `0.5.1` and python 3.7.9, and it worked here or at least it didn't raise any error

this is the code I used:

```
nb = nbformat.read(notebook_filename, as_version=4)
timeout = 60
allow_errors = False

c = NotebookClient(
    nb,
    timeout=timeout,
    allow_errors=allow_errors,
    record_timing=True,
)
c.execute(cwd=cwd)
```

where `cwd` and `notebook_filename` points to my local storage.

let me know if you have a specific code about this problem that I can try here.

**Comment by davidbrochart** [comment]
@alex-treebeard should this issue be closed?

**Comment by alex-treebeard** [comment]
Yes it hasn't reappeared so let's close it.
