### ISSUE TITLE
nbclient 0.5.11 not compatible with  traitlets 4.3.3

### ISSUE THREAD

**Issue by hongfei0224** [jupyter/nbclient#203]
I have nbclient 0.5.11 with traitlets 4.3.3.

`import nbclient `
would give error below:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/nbclient/__init__.py", line 6, in <module>
    from .client import NotebookClient, execute  # noqa: F401
  File "/usr/local/lib/python3.7/site-packages/nbclient/client.py", line 18, in <module>
    from traitlets import (
ImportError: cannot import name 'Callable' from 'traitlets' (/usr/local/lib/python3.7/site-packages/traitlets/__init__.py)
```

**Comment by davidbrochart** [comment]
Thanks for reporting, indeed nbclient now needs `traitlets>=5.0.0`.
