### ISSUE TITLE
0.6.1: sphinx faiils because missing file

### ISSUE THREAD

**Issue by kloczek** [jupyter/nbclient#227]
Looks like just released 0.6.1 has some small flaw.
```console
+ /usr/bin/sphinx-build -n -T -b man docs build/sphinx/man
Running Sphinx v4.5.0
making output directory... done

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 272, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 237, in __init__
    self.config.setup(self)
  File "/home/tkloczko/rpmbuild/BUILD/nbclient-0.6.1/docs/conf.py", line 193, in setup
    exec(compile(f.read(), autogen_config, "exec"), {})
  File "/home/tkloczko/rpmbuild/BUILD/nbclient-0.6.1/docs/autogen_config.py", line 46, in <module>
    with open(destination, "w") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/tkloczko/rpmbuild/BUILD/nbclient-0.6.1/reference/config_options.rst'

Exception occurred:
  File "/home/tkloczko/rpmbuild/BUILD/nbclient-0.6.1/docs/autogen_config.py", line 46, in <module>
    with open(destination, "w") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/tkloczko/rpmbuild/BUILD/nbclient-0.6.1/reference/config_options.rst'
The full traceback has been saved in /tmp/sphinx-err-bv8v05np.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

**Comment by davidbrochart** [comment]
Thanks for reporting @kloczek, I opened #228.
