### ISSUE TITLE
Async not awaited in some tests. 

### ISSUE THREAD

**Issue by MSeal** [jupyter/nbclient#33]
Looks like it's mostly benign around test mocking not being updated to await always, but we probably want to remove the warnings before releasing in case there's a bug associated? Thoughts @davidbrochart 

```
=============================== warnings summary ===============================
nbclient/tests/test_client.py::TestRunCell::test_deadline_iopub
  /usr/lib/python3.6/unittest/mock.py:684: RuntimeWarning: coroutine 'make_async.<locals>._' was never awaited
    return object.__setattr__(self, name, value)

nbclient/tests/test_client.py::TestRunCell::test_display_data_message
nbclient/tests/test_client.py::TestRunCell::test_unknown_comm_message
  /usr/lib/python3.6/unittest/mock.py:1898: RuntimeWarning: coroutine 'make_async.<locals>._' was never awaited
    self.name = name

nbclient/tests/test_client.py::TestRunCell::test_eventual_deadline_iopub
  /home/mseal/Workspace/nbclient/nbclient/tests/test_client.py:719: RuntimeWarning: coroutine 'make_async.<locals>._' was never awaited
    message_mock.side_effect = message_seq(list(message_mock.side_effect)[:-1])

nbclient/tests/test_client.py::TestRunCell::test_eventual_deadline_iopub
  /home/mseal/.py3local/lib/python3.6/site-packages/traitlets/traitlets.py:510: RuntimeWarning: coroutine 'make_async.<locals>._' was never awaited
    if meth_name in cls.__dict__:
```

**Comment by MSeal** [comment]
Hmm looks like it might be an actual issue when I was testing with papermill (some changes needed to make that work as well):

```
sys:1: RuntimeWarning: coroutine 'NotebookClient._wait_for_reply' was never awaited
Executing: 100%|████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [01:04<00:00, 10.02s/cell]
Traceback (most recent call last):
  File "/home/mseal/.py3local/bin/papermill", line 11, in <module>
    load_entry_point('papermill', 'console_scripts', 'papermill')()
  File "/home/mseal/.py3local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/mseal/.py3local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/mseal/.py3local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mseal/.py3local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/mseal/Workspace/papermill/papermill/cli.py", line 235, in papermill
    execution_timeout=execution_timeout,
  File "/home/mseal/Workspace/papermill/papermill/execute.py", line 104, in execute_notebook
    **engine_kwargs
  File "/home/mseal/Workspace/papermill/papermill/engines.py", line 49, in execute_notebook_with_engine
    return self.get_engine(engine_name).execute_notebook(nb, kernel_name, **kwargs)
  File "/home/mseal/Workspace/papermill/papermill/engines.py", line 343, in execute_notebook
    cls.execute_managed_notebook(nb_man, kernel_name, log_output=log_output, **kwargs)
  File "/home/mseal/Workspace/papermill/papermill/engines.py", line 402, in execute_managed_notebook
    return PapermillNotebookClient(nb_man, **final_kwargs).execute()
  File "/home/mseal/Workspace/papermill/papermill/clientwrap.py", line 40, in execute
    self.nb.metadata['language_info'] = info_msg['content']['language_info']
TypeError: 'coroutine' object is not subscriptable
sys:1: RuntimeWarning: coroutine 'NotebookClient._wait_for_reply' was never awaited
```

**Comment by MSeal** [comment]
I'll keep doing some testing on this as I workout changes needed for papermill to continue working as intended. It's possible a different change I made caused the warning in tests to crop up as an execution error.

**Comment by davidbrochart** [comment]
The warnings are due to message mocking now being async, which creates coroutines in `prepare_cell_mocks`. It also appends an idle message to terminate the execute requests, but some tests (e.g. `test_eventual_deadline_iopub`) don't process all messages on purpose, leaving this last message not awaited.
I'm not sure how we should deal with this, maybe by awaiting the unprocessed messages at the end of the tests, or by having `prepare_cell_mocks` optionally append the idle message. We could also disable this warning altogether.

**Comment by MSeal** [comment]
Closing for now, don't think we need to take any action atm
