### ISSUE TITLE
Impossible to execute notebooks containing the %gui qt magic?

### ISSUE THREAD

**Issue by jni** [jupyter/nbclient#97]
When executing a notebook containing a %gui qt magic, nbclient fails with the error:

<details>

<summary>

```pytb
AttributeError: 'IPythonKernel' object has no attribute 'app'
```

</summary>

```pytb
[IPKernelApp] ERROR | Exception in control handler:
Traceback (most recent call last):
  File "/Users/jni/conda/envs/all/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 201, in dispatch_control
    yield gen.maybe_future(handler(self.control_stream, idents, msg))
  File "/Users/jni/conda/envs/all/lib/python3.8/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/Users/jni/conda/envs/all/lib/python3.8/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/Users/jni/conda/envs/all/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 683, in shutdown_request
    content = yield gen.maybe_future(self.do_shutdown(parent['content']['restart']))
  File "/Users/jni/conda/envs/all/lib/python3.8/site-packages/ipykernel/ipkernel.py", line 450, in do_shutdown
    self.shell.exit_now = True
  File "/Users/jni/conda/envs/all/lib/python3.8/site-packages/traitlets/traitlets.py", line 585, in __set__
    self.set(obj, value)
  File "/Users/jni/conda/envs/all/lib/python3.8/site-packages/traitlets/traitlets.py", line 574, in set
    obj._notify_trait(self.name, old_value, new_value)
  File "/Users/jni/conda/envs/all/lib/python3.8/site-packages/traitlets/traitlets.py", line 1134, in _notify_trait
    self.notify_change(Bunch(
  File "/Users/jni/conda/envs/all/lib/python3.8/site-packages/traitlets/traitlets.py", line 1176, in notify_change
    c(change)
  File "/Users/jni/conda/envs/all/lib/python3.8/site-packages/ipykernel/zmqshell.py", line 476, in _update_exit_now
    exit_hook(self.kernel)
  File "/Users/jni/conda/envs/all/lib/python3.8/site-packages/ipykernel/eventloops.py", line 136, in loop_qt_exit
    kernel.app.exit()
AttributeError: 'IPythonKernel' object has no attribute 'app'
Out[6]:
{'cells': [{'cell_type': 'code',
   'execution_count': 1,
   'metadata': {'execution': {'iopub.status.busy': '2020-08-10T13:24:48.262059Z',
     'iopub.execute_input': '2020-08-10T13:24:48.262847Z',
     'iopub.status.idle': '2020-08-10T13:24:48.354775Z',
     'shell.execute_reply': '2020-08-10T13:24:48.356131Z'}},
   'outputs': [],
   'source': '%gui qt\n%matplotlib qt'},
  {'cell_type': 'code',
   'execution_count': 2,
   'metadata': {'execution': {'iopub.status.busy': '2020-08-10T13:24:48.359983Z',
     'iopub.execute_input': '2020-08-10T13:24:48.360516Z',
     'iopub.status.idle': '2020-08-10T13:24:48.537911Z',
     'shell.execute_reply': '2020-08-10T13:24:48.538351Z'}},
   'outputs': [{'output_type': 'execute_result',
     'metadata': {},
     'data': {'text/plain': '<matplotlib.collections.PathCollection at 0x7f837a09feb0>'},
     'execution_count': 2}],
   'source': 'import matplotlib.pyplot as plt\nimport numpy as np\n\n\nplt.scatter(*np.random.random((2, 10)))'}],
 'metadata': {'kernelspec': {'display_name': 'Python 3',
   'language': 'python',
   'name': 'python3'},
  'language_info': {'name': 'python',
   'version': '3.8.2',
   'mimetype': 'text/x-python',
   'codemirror_mode': {'name': 'ipython', 'version': 3},
   'pygments_lexer': 'ipython3',
   'nbconvert_exporter': 'python',
   'file_extension': '.py'}},
 'nbformat': 4,
 'nbformat_minor': 4}
```

</details>

I've provided a minimal notebook in [this gist](https://gist.github.com/jni/077cc4d8e40d56e5bf71dd03c80db89b).

In turn, the nbclient code to run it (basically lifted from the getting started guide):

```python
import nbformat
from nbclient import NotebookClient
with open('Untitled.ipynb') as f:
    nb = nbformat.read(f, as_version=4)

client = NotebookClient(nb, timeout=15, kernel_name='python3')
client.execute()
```

xref: https://github.com/executablebooks/jupyter-book/issues/840

**Comment by Carreau** [comment]
I'm not too sure,  I think app is made to work with examples/embedding/ipkernel_qtapp.py, and otherwise we likely don't want to call any `sys-exit()-ish` as – as you showed this can in-process.

**Comment by GenevieveBuckley** [comment]
Perhaps I've searched poorly, but where is `examples/embedding/ipkernel_qtapp.py`? Thank you @Carreau

**Comment by GenevieveBuckley** [comment]
Dug around a bit more, found it here: [`ipykernel/examples/embedding/ipkernel_qtapp.py`](https://github.com/ipython/ipykernel/blob/master/examples/embedding/ipkernel_qtapp.py)

**Comment by GenevieveBuckley** [comment]
Interesting, I can run @jni's example notebook with [runipy](https://github.com/paulgb/runipy). That project is no longer maintained now that jupyter_client has an execute method, but perhaps the differences between the two projects will give us a clue.

Sadly I wasn't able to run this similar notebook with the `%gui qt` magic, that's closer to what we actually want to do.
```python
# cell 1
%gui qt

# cell 2
import napari
viewer = napari.Viewer()
```

<details>
  <summary>runipy error details - Click to expand!</summary>

```python-traceback
10/26/2020 06:22:54 PM INFO: Running cell:
%gui qt

10/26/2020 06:22:54 PM INFO: Cell returned
10/26/2020 06:22:54 PM INFO: Running cell:
import napari

viewer = napari.Viewer()

10/26/2020 06:22:57 PM INFO: Cell raised uncaught exception:
[1;31m---------------------------------------------------------------------------[0m
[1;31mRuntimeError[0m                              Traceback (most recent call last)
[1;32m<ipython-input-2-63db54b875ee>[0m in [0;36m<module>[1;34m[0m
[0;32m      1[0m [1;32mimport[0m [0mnapari[0m[1;33m[0m[1;33m[0m[0m
[0;32m      2[0m [1;33m[0m[0m
[1;32m----> 3[1;33m [0mviewer[0m [1;33m=[0m [0mnapari[0m[1;33m.[0m[0mViewer[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m
[1;32mc:\users\genevieve\anaconda3\envs\napari\lib\site-packages\napari\viewer.py[0m in [0;36m__init__[1;34m(self, title, ndisplay, order, axis_labels, show)[0m
[0;32m     64[0m                 [1;34m" Then, restart IPython."[0m[1;33m[0m[1;33m[0m[0m
[0;32m     65[0m             )
[1;32m---> 66[1;33m             [1;32mraise[0m [0mRuntimeError[0m[1;33m([0m[0mmessage[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     67[0m [1;33m[0m[0m
[0;32m     68[0m         [1;32mif[0m [0mperf_config[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;31mRuntimeError[0m: napari requires a Qt event loop to run. To create one, try one of the following:
  - use the `napari.gui_qt()` context manager. See https://github.com/napari/napari/tree/master/examples for usage examples.
  - In IPython or a local Jupyter instance, use the `%gui qt` magic command.
  - Launch IPython with the option `--gui=qt`.
  - (recommended) in your IPython configuration file, add or uncomment the line `c.TerminalIPythonApp.gui = 'qt'`. Then, restart IPython.
10/26/2020 06:22:57 PM INFO: Shutdown kernel
10/26/2020 06:22:57 PM WARNING: Exiting with nonzero exit status
```
</details>

**Comment by jni** [comment]
thanks @GenevieveBuckley for investigating!

> Sadly I wasn't able to run this similar notebook with the `%gui qt` magic

Does it help to add a sleep cell?

```python
# cell 1
%gui qt

# cell 2
import time
time.sleep(5)

# cell 3
import napari
viewer = napari.Viewer()
```
?

**Comment by GenevieveBuckley** [comment]
> Does it help to add a sleep cell?

Yes! That works now!!! 🎉 

Let's move this conversation back over to https://github.com/napari/napari/issues/1568 while we discuss things that are *not* `nbclient` (I don't want to spam people watching this repository unnecessarily)

**Comment by GenevieveBuckley** [comment]
This issue can be closed, we've worked out what our problem was.

For anyone else running in to the same thing: the problem with nbclient is that we need a separate `time.sleep(1)` cell, that comes *after* the cell with the `%gui qt` magic, and *before* the cell where we import the library that needs to use Qt. The magic is an asynchronous process, and for reasons that remain mysterious to me you can't put the sleep in the same cell as the magic (which is what I tried earlier).

To modify @jni's example notebook from the gist slightly, this now works:
```python
# cell 1
%gui qt
%matplotlib qt

# cell 2
import time
time.sleep(2)

# cell 3
import matplotlib.pyplot as plt
import numpy as np

plt.scatter(*np.random.random((2, 10)))
```

**Comment by GenevieveBuckley** [comment]
Thank you for your help @Carreau

**Comment by jni** [comment]
Holy moly! :tada: thank you for putting it all together, @GenevieveBuckley!
